#!/usr/bin/env bash
#
# Bootstraps the Unity Catalog governance layer:
#   1. analytics catalog + bronze/silver/gold schemas (medallion)
#   2. Sample users (engineer, analyst) mirroring the Keycloak realm
#   3. RBAC grants demonstrating least-privilege roles
#
# Idempotent: re-running is safe (creates are guarded).
#
set -uo pipefail

cd /home/unitycatalog

CONF=/home/unitycatalog/etc/conf
UC_URI="${UC_URI:-http://unitycatalog:8080}"
CATALOG="${UC_CATALOG:-analytics}"
BUCKET="${LAKEHOUSE_BUCKET:-lakehouse}"

echo ">> Waiting for admin token.txt to be generated by the UC server..."
for _ in $(seq 1 60); do
  [ -s "${CONF}/token.txt" ] && break
  sleep 2
done
if [ ! -s "${CONF}/token.txt" ]; then
  echo "!! token.txt not found - is server.authorization enabled? Aborting." >&2
  exit 1
fi
TOKEN="$(cat "${CONF}/token.txt")"

uc() { bin/uc --server "${UC_URI}" --auth_token "${TOKEN}" "$@"; }

echo ">> Creating catalog + medallion schemas"
uc catalog create --name "${CATALOG}" --comment "Governed analytics lakehouse" 2>/dev/null || true
for schema in bronze silver gold; do
  uc schema create --catalog "${CATALOG}" --name "${schema}" \
    --comment "${schema} layer" 2>/dev/null || true
done

echo ">> Creating users (must match Keycloak realm emails)"
uc user create --name "Data Engineer" --email engineer@platform.local 2>/dev/null || true
uc user create --name "Data Analyst"  --email analyst@platform.local  2>/dev/null || true

grant() {
  # grant <securable_type> <name> <privilege> <principal>
  uc permission create --securable_type "$1" --name "$2" \
    --privilege "$3" --principal "$4" 2>/dev/null || true
}

echo ">> RBAC: engineer = full builder on all layers"
grant catalog "${CATALOG}" "USE CATALOG" engineer@platform.local
for schema in bronze silver gold; do
  grant schema "${CATALOG}.${schema}" "USE SCHEMA"   engineer@platform.local
  grant schema "${CATALOG}.${schema}" "CREATE TABLE" engineer@platform.local
  grant schema "${CATALOG}.${schema}" "MODIFY"       engineer@platform.local
  grant schema "${CATALOG}.${schema}" "SELECT"       engineer@platform.local
done

echo ">> RBAC: analyst = read-only on the gold layer"
grant catalog "${CATALOG}"        "USE CATALOG" analyst@platform.local
grant schema  "${CATALOG}.gold"   "USE SCHEMA"  analyst@platform.local
grant schema  "${CATALOG}.gold"   "SELECT"      analyst@platform.local

# ---------------------------------------------------------------------------
# Automation service accounts (identity is seeded in the Keycloak realm as the
# confidential clients `sa-platform-automation` + `sa-team-analytics`; here we
# register their UC principals + data-plane grants so a fresh `down -v && up`
# comes up with a WORKING automation plane -- no manual provisioning step).
# These are the DAG-run identities: Dagster exchanges each SA's client-creds for
# a UC token (see data_platform.uc_identity). They build the full medallion, so
# they get the data-engineer builder template. Additional SAs are still created
# on demand via the delegated-admin flow (provision_service_account.py).
# UC principal email MUST match each client's hardcoded `email` claim.
# ---------------------------------------------------------------------------
echo ">> Registering automation service-account principals"
uc user create --name "Platform Automation SA" --email sa-platform-automation@platform.local 2>/dev/null || true
uc user create --name "Analytics Team SA"       --email sa-team-analytics@platform.local     2>/dev/null || true

for sa_email in sa-platform-automation@platform.local sa-team-analytics@platform.local; do
  echo ">> RBAC: ${sa_email} = builder on all layers (data-engineer template)"
  grant catalog "${CATALOG}" "USE CATALOG" "${sa_email}"
  for schema in bronze silver gold; do
    grant schema "${CATALOG}.${schema}" "USE SCHEMA"   "${sa_email}"
    grant schema "${CATALOG}.${schema}" "CREATE TABLE" "${sa_email}"
    grant schema "${CATALOG}.${schema}" "MODIFY"       "${sa_email}"
    grant schema "${CATALOG}.${schema}" "SELECT"       "${sa_email}"
  done
done

echo ">> Bootstrap complete. Current catalog/schema layout:"
uc schema list --catalog "${CATALOG}" || true
